---
chdir: "/var/www/rubyquiz/current"
environment: production
address: 0.0.0.0
port: 5000
timeout: 90
log: /var/www/rubyquiz/shared/log/thin.log
pid: /var/www/rubyquiz/shared/tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
tag: rubyquiz
